### ISSUE TITLE
A better way to get user home directory

### ISSUE THREAD

**Issue by Gnouc** [aspiers/stow#10]
Using `$ENV{HOME}` to get the user home directory is not always *safe*, example:
```
unset HOME; perl -le 'print $ENV{HOME}'
```

and also using `glob` with tilde expansion, since when it's relied on `HOME` variable, and the result is unspecified when [HOME is unset](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01).

Should we add a method to get the user home directory more safely, using something like [getpwnam](http://pubs.opengroup.org/onlinepubs/9699919799/functions/getpwnam.html)?

**Comment by aspiers** [comment]
I'm not convinced it's right to change the current behaviour, because occasionally the caller might deliberately set `$HOME` to a different value in which case it would be bad to ignore it.  Why do you think anyone would do `unset HOME`?  That doesn't make any sense to me.

**Comment by Gnouc** [comment]
@aspiers: It's not only the case `HOME ` is unset, but also when it's changed, `perl` will get it value, even in taint mode:
```
$ HOME=a perl -Tle 'print $ENV{HOME}'
a
```
The user may not change the `HOME`, but someone can make them change it without any noticeable. The ideal is to safely handle any external input. At this time, it can make no impact, but we don't know when it will in the future.

**Comment by aspiers** [comment]
Stow doesn't provide any privilege escalation, so I don't see why it needs to be responsible for security-based input validation.  IOW it already assumes a trusted environment.  If you can run Stow, you can already do much nastier things directly rather than by running Stow.

If Stow is fronted by something with a different security model, such as `sudo` or a web frontend, then it is the responsibility of that frontend to ensure that Stow is run in a safe way.  However I don't want to cripple Stow based on non-existent threats.  It seems more likely to me that someone would have a valid reason for changing `HOME` than that someone would try some attack vector via Stow with a modified `HOME`.
